// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PostsImport } from './routes/posts'
import { Route as IndexImport } from './routes/index'
import { Route as PostsPostIdImport } from './routes/posts.$postId'
import { Route as PostsPostIdDeepImport } from './routes/posts_.$postId.deep'

// Create Virtual Routes

const LayoutLazyImport = createFileRoute('/_layout')()
const PostsIndexLazyImport = createFileRoute('/posts/')()
const LayoutLayoutBLazyImport = createFileRoute('/_layout/layout-b')()
const LayoutLayoutALazyImport = createFileRoute('/_layout/layout-a')()

// Create/Update Routes

const LayoutLazyRoute = LayoutLazyImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_layout.lazy').then((d) => d.Route))

const PostsRoute = PostsImport.update({
  path: '/posts',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexLazyRoute = PostsIndexLazyImport.update({
  path: '/',
  getParentRoute: () => PostsRoute,
} as any).lazy(() => import('./routes/posts.index.lazy').then((d) => d.Route))

const LayoutLayoutBLazyRoute = LayoutLayoutBLazyImport.update({
  path: '/layout-b',
  getParentRoute: () => LayoutLazyRoute,
} as any).lazy(() =>
  import('./routes/_layout/layout-b.lazy').then((d) => d.Route),
)

const LayoutLayoutALazyRoute = LayoutLayoutALazyImport.update({
  path: '/layout-a',
  getParentRoute: () => LayoutLazyRoute,
} as any).lazy(() =>
  import('./routes/_layout/layout-a.lazy').then((d) => d.Route),
)

const PostsPostIdRoute = PostsPostIdImport.update({
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)

const PostsPostIdDeepRoute = PostsPostIdDeepImport.update({
  path: '/posts/$postId/deep',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/posts': {
      preLoaderRoute: typeof PostsImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutLazyImport
      parentRoute: typeof rootRoute
    }
    '/posts/$postId': {
      preLoaderRoute: typeof PostsPostIdImport
      parentRoute: typeof PostsImport
    }
    '/_layout/layout-a': {
      preLoaderRoute: typeof LayoutLayoutALazyImport
      parentRoute: typeof LayoutLazyImport
    }
    '/_layout/layout-b': {
      preLoaderRoute: typeof LayoutLayoutBLazyImport
      parentRoute: typeof LayoutLazyImport
    }
    '/posts/': {
      preLoaderRoute: typeof PostsIndexLazyImport
      parentRoute: typeof PostsImport
    }
    '/posts/$postId/deep': {
      preLoaderRoute: typeof PostsPostIdDeepImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  PostsRoute.addChildren([PostsPostIdRoute, PostsIndexLazyRoute]),
  LayoutLazyRoute.addChildren([LayoutLayoutALazyRoute, LayoutLayoutBLazyRoute]),
  PostsPostIdDeepRoute,
])
